//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AugmentedCandle
    {
        public System.Guid Id { get; set; }
        public int Symbol { get; set; }
        public int Timeframe { get; set; }
        public System.DateTime Time { get; set; }
        public double Open { get; set; }
        public double High { get; set; }
        public double Low { get; set; }
        public double Close { get; set; }
        public int Volume { get; set; }
        public double Sma50 { get; set; }
        public double Sma100 { get; set; }
        public double Ema12 { get; set; }
        public double Ema26 { get; set; }
        public double MACDLine { get; set; }
        public double SignalLine { get; set; }
        public double Histogram { get; set; }
        public double RSI { get; set; }
        public Nullable<double> Ema50 { get; set; }
    }
}
