//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketDataCredential
    {
        public System.Guid Id { get; set; }
        public int Symbol { get; set; }
        public int Timeframe { get; set; }
        public string ApiKey { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int CallCounter { get; set; }
        public System.DateTime RefreshDate { get; set; }
    }
}
