//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Note
    {
        public System.Guid NidNote { get; set; }
        public System.Guid GroupId { get; set; }
        public string Title { get; set; }
        public string NoteContent { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual NoteGroup NoteGroup { get; set; }
    }
}
