//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutineProgress
    {
        public System.Guid NidRoutineProgress { get; set; }
        public System.Guid RoutineId { get; set; }
        public System.DateTime ProgressDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Routine Routine { get; set; }
    }
}
