//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Progresses = new HashSet<Progress>();
        }
    
        public System.Guid NidSchedule { get; set; }
        public System.Guid TaskId { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ICollection<Progress> Progresses { get; set; }
        public virtual Task Task { get; set; }
    }
}
