//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signal
    {
        public Signal()
        {
            this.SignalResults = new HashSet<SignalResult>();
        }
    
        public System.Guid Id { get; set; }
        public int Symbol { get; set; }
        public int Timeframe { get; set; }
        public int SignalType { get; set; }
        public System.DateTime StartDate { get; set; }
        public double EnterPrice { get; set; }
        public double StopLostPrice { get; set; }
        public double TakeProfitPrice { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsActive { get; set; }
        public byte WinChanceEstimate { get; set; }
        public int SignalProvider { get; set; }
    
        public virtual ICollection<SignalResult> SignalResults { get; set; }
    }
}
