//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public System.Guid NidTask { get; set; }
        public System.Guid GoalId { get; set; }
        public string Title { get; set; }
        public bool TaskStatus { get; set; }
        public byte TaskWeight { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual Goal Goal { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual User User { get; set; }
    }
}
