//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid NidTransaction { get; set; }
        public byte TransactionType { get; set; }
        public System.Guid PayerAccount { get; set; }
        public System.Guid RecieverAccount { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string TransactionReason { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.Guid> TransactionGroupId { get; set; }
    
        public virtual User User { get; set; }
    }
}
