//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Goals = new HashSet<Goal>();
            this.NoteGroups = new HashSet<NoteGroup>();
            this.Progresses = new HashSet<Progress>();
            this.Routines = new HashSet<Routine>();
            this.Shields = new HashSet<Shield>();
            this.Tasks = new HashSet<Task>();
            this.Transactions = new HashSet<Transaction>();
            this.Accounts = new HashSet<Account>();
            this.TransactionGroups = new HashSet<TransactionGroup>();
        }
    
        public System.Guid NidUser { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public bool IsDisabled { get; set; }
    
        public virtual ICollection<Goal> Goals { get; set; }
        public virtual ICollection<NoteGroup> NoteGroups { get; set; }
        public virtual ICollection<Progress> Progresses { get; set; }
        public virtual ICollection<Routine> Routines { get; set; }
        public virtual ICollection<Shield> Shields { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<TransactionGroup> TransactionGroups { get; set; }
    }
}
